//
// Created by Devilast on 6/20/2021.
//

#ifndef EVENTSYSTEM_ENGINEDEFINITIONS_H
#define EVENTSYSTEM_ENGINEDEFINITIONS_H

#define SNV_CALL_CONVECTION_API __cdecl

#endif //EVENTSYSTEM_ENGINEDEFINITIONS_H
