name: Build

on:
  pull_request:
    branches: [ master ]

env:
  VULKAN_VERSION: "1.2.189.2"
  VULKAN_SDK: "C:/VulkanSDK/1.2.189.2/"
  PYTHON_VERSION: "3.9.6"

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019]
        compiler: [msvc]
        build_type: [Debug, Release]

    steps:
      # lfs might fail
      # reason: https://github.com/actions/checkout/issues/270
      # fix: https://stackoverflow.com/questions/61463578/github-actions-actions-checkoutv2-lfs-true-flag-not-converting-pointers-to-act
      - name: Get source code
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Install Vulkan SDK
        shell: bash
        run: |
          curl -O https://sdk.lunarg.com/sdk/download/${{ env.VULKAN_VERSION }}/windows/vulkan_sdk.exe
          ./vulkan_sdk.exe --accept-licenses --default-answer --confirm-command install

      - name: Setup VisualStudio Environment
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          architecture: 'x64'

      - name: Install conan
        run: |
          pip install wheel setuptools
          pip install conan

      - name: Run conan-init.ps1
        shell: powershell
        run: ./conan-init.ps1

      - name: Configure CMake
        run: cmake . --preset ${{ matrix.compiler }}_${{ matrix.build_type }}

      - name: Build
        run: cmake --build --preset ${{ matrix.compiler }}_${{ matrix.build_type }}
